# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

PATH="$HOME/.config/emacs/bin/:$PATH"
PATH="$HOME/go/bin:$PATH"
PATH="/usr/local/bin:$PATH"

# Use Fuzzy search
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash
source /usr/share/bash-completion/bash_completion

# To remove all but the last identical command,
# and commands that start with a space:
export HISTCONTROL="erasedups:ignorespace"

export EDITOR="/usr/bin/emacsclient"

# Allows the GPG Agent to ask for your password when e.g., using Sops to en- or
# decrypt a file.
GPG_TTY=$(tty)
export GPG_TTY

eval "$(starship init bash)"
source <(oc completion bash)
source <(kustomize completion bash)
source <(mario completion bash)
