# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

PATH="$HOME/.emacs.d/bin/:$PATH"
PATH="$HOME/go/bin:$PATH"
PATH="/usr/local/bin:$PATH"

# Use Fuzzy search
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash
source /usr/share/bash-completion/bash_completion

# To remove all but the last identical command,
# and commands that start with a space:
export HISTCONTROL="erasedups:ignorespace"

eval "$(starship init bash)"
