# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi

# Toolbox variables
if [ "$HOSTNAME" == "toolbox" ]; then
    PATH="$HOME/.emacs.d/bin:$PATH"
fi

# Container specific $PATH's
if [ -f /run/.toolboxenv ]; then
  source /run/.containerenv
  if [ "$name" = "golang1.17" ]; then
    GOROOT=/usr/local/go
    GOPATH=$HOME/go
    PATH=$GOPATH/bin:$GOROOT/bin:$PATH
  fi
fi 

export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

eval "$(starship init bash)"

# Use Fuzzy search
source /usr/share/fzf/shell/key-bindings.bash

unset rc
